# fly.toml app configuration file generated for whoogle-kdev on 2023-07-31T18:55:32+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "whoogle-kdev"
primary_region = "ams"

[build]
  image = "koval01/whoogle-search-kdev:latest"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
