apiVersion: v2
name: whoogle
description: A self hosted search engine on Kubernetes
type: application
version: 0.1.0
appVersion: 0.7.5

icon: https://github.com/koval01/whoogle-search-kdev/raw/main/app/static/img/favicon/favicon-96x96.png

sources:
  - https://github.com/koval01/whoogle-search-kdev
  - https://gitlab.com/koval01/whoogle-search-kdev
  - https://gogs.koval01.com/koval01/whoogle-search-kdev

keywords:
  - whoogle
  - degoogle
  - search
  - google
  - search-engine
  - privacy
  - tor
  - python
